/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TagToPagePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_autocomplete = require("@codemirror/autocomplete");
var LANG = {
  zh: {
    settingHeader: "Tag to Page",
    pluginDesc: "\u70B9\u51FB #\u6807\u7B7E \u65F6\u76F4\u63A5\u8DF3\u8F6C\u5230 [[\u9875\u9762]]\uFF0C\u800C\u4E0D\u662F\u6253\u5F00\u6807\u7B7E\u641C\u7D22\u9762\u677F\u3002\u7ED3\u5408\u53CD\u94FE\u9762\u677F\u4F7F\u7528\uFF0C\u8FD8\u539F Logseq \u7684\u6807\u7B7E\u6D4F\u89C8\u4F53\u9A8C\u3002",
    preferences: "\u504F\u597D\u8BBE\u7F6E",
    preferencesDesc: "\u9009\u62E9\u8BBE\u7F6E\u754C\u9762\u8BED\u8A00\uFF0C\u5E76\u6309\u9700\u8C03\u6574\u6807\u7B7E\u9875\u9762\u884C\u4E3A\u3002",
    language: "\u754C\u9762\u8BED\u8A00",
    languageDesc: "\u9009\u62E9\u63D2\u4EF6\u8BBE\u7F6E\u754C\u9762\u4F7F\u7528\u7684\u8BED\u8A00\u3002",
    behavior: "\u6807\u7B7E\u884C\u4E3A",
    behaviorDesc: "\u63A7\u5236\u70B9\u51FB\u6807\u7B7E\u548C\u8F93\u5165 # \u65F6\u7684\u9875\u9762\u8DF3\u8F6C\u4F53\u9A8C\u3002",
    autocompleteName: "\u8F93\u5165 # \u65F6\u663E\u793A\u9875\u9762\u8865\u5168",
    autocompleteDesc: "\u5F00\u542F\u540E\uFF0C\u8F93\u5165 # \u4F1A\u63D0\u793A\u5339\u914D\u7684\u7B14\u8BB0\u6587\u4EF6\u540D\u548C\u522B\u540D\u3002\u5207\u6362\u5F00\u5173\u540E\u63D2\u4EF6\u4F1A\u81EA\u52A8\u91CD\u8F7D\u4EE5\u5E94\u7528\u8BBE\u7F6E\u3002",
    autocompleteNotice: "\u4F7F\u7528\u63D0\u793A",
    autocompleteNoticeDesc: "\u9875\u9762\u8865\u5168\u4F1A\u66FF\u6362 Obsidian \u9ED8\u8BA4\u7684 [[ \u9875\u9762\u9009\u62E9\u5668\uFF0C\u5E76\u53EF\u80FD\u589E\u52A0\u626B\u63CF\u5F00\u9500\uFF1B\u9047\u5230\u5F02\u5E38\u65F6\u53EF\u5173\u95ED\u6B64\u9009\u9879\u3002",
    repository: "GitHub \u9879\u76EE\u4E3B\u9875"
  },
  en: {
    settingHeader: "Tag to Page",
    pluginDesc: "Click #tag to navigate directly to [[page]] instead of opening the tag search panel. Use with the Backlinks pane for a Logseq-like tag browsing experience.",
    preferences: "Preferences",
    preferencesDesc: "Choose the settings language and adjust tag-page behavior.",
    language: "Interface language",
    languageDesc: "Choose the language used by this settings page.",
    behavior: "Tag behavior",
    behaviorDesc: "Control tag clicks and page suggestions while typing #.",
    autocompleteName: "Page-name suggestions with #",
    autocompleteDesc: "When on, typing # suggests matching file names and frontmatter aliases. The plugin reloads automatically after this setting changes.",
    autocompleteNotice: "Please note",
    autocompleteNoticeDesc: "Page completion replaces Obsidian's default [[ link picker and may add scanning overhead. Turn it off if you notice unexpected behavior.",
    repository: "GitHub repository"
  }
};
var DEFAULT_SETTINGS = {
  autocompleteOn: false,
  language: "zh"
};
var TagToPagePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerDomEvent(document, "click", this.onTagClick.bind(this), true);
    this.registerDomEvent(document, "touchend", this.onTagTouchEnd.bind(this), { capture: true, passive: false });
    if (this.settings.autocompleteOn) {
      this.registerAutocompleteOverride();
    }
    this.addSettingTab(new TagToPageSettingTab(this.app, this));
  }
  // ── click handler (Reading View + Live Preview) ──
  onTagTouchEnd(evt) {
    var _a;
    const touch = evt.changedTouches[0];
    const target = document.elementFromPoint(touch.clientX, touch.clientY);
    if (!target)
      return;
    const tagEl = target.closest(".tag, .cm-hashtag");
    if (!tagEl)
      return;
    const contentArea = tagEl.closest(
      ".markdown-preview-view, .cm-editor, .markdown-source-view"
    );
    if (!contentArea)
      return;
    evt.stopPropagation();
    evt.preventDefault();
    let tagName = ((_a = tagEl.textContent) != null ? _a : "").trim();
    tagName = tagName.replace(/^#/, "").trim();
    if (!tagName)
      return;
    this.navigateToTagPage(tagName, false);
  }
  onTagClick(evt) {
    var _a;
    if (evt.button !== 0)
      return;
    const target = evt.target;
    const tagEl = target.closest(".tag, .cm-hashtag");
    if (!tagEl)
      return;
    const contentArea = tagEl.closest(
      ".markdown-preview-view, .cm-editor, .markdown-source-view"
    );
    if (!contentArea)
      return;
    evt.stopPropagation();
    evt.preventDefault();
    let tagName = ((_a = tagEl.textContent) != null ? _a : "").trim();
    tagName = tagName.replace(/^#/, "").trim();
    if (!tagName)
      return;
    this.navigateToTagPage(tagName, evt.ctrlKey || evt.metaKey);
  }
  // ── navigation ──
  async navigateToTagPage(tagName, openInNewLeaf) {
    const { vault, metadataCache, workspace } = this.app;
    try {
      let file = metadataCache.getFirstLinkpathDest(tagName, "");
      if (!file)
        file = this.findFileByAlias(tagName);
      if (!file) {
        await this.ensureParentDirectories(tagName);
        file = await vault.create(tagName + ".md", "");
      }
      await workspace.openLinkText(file.basename, "", openInNewLeaf);
    } catch (err) {
      console.error("Tag to Page: failed to navigate", err);
    }
  }
  findFileByAlias(alias) {
    const { vault, metadataCache } = this.app;
    const target = alias.toLowerCase();
    for (const file of vault.getMarkdownFiles()) {
      const cache = metadataCache.getCache(file.path);
      const fm = cache == null ? void 0 : cache.frontmatter;
      if (!fm)
        continue;
      for (const key of ["alias", "aliases"]) {
        const val = fm[key];
        const list = typeof val === "string" ? [val] : Array.isArray(val) ? val.filter((v) => typeof v === "string") : [];
        if (list.some((a) => a.toLowerCase() === target))
          return file;
      }
    }
    return null;
  }
  async ensureParentDirectories(tagName) {
    const parts = tagName.split("/");
    if (parts.length <= 1)
      return;
    for (let i = 1; i < parts.length; i++) {
      const dirPath = parts.slice(0, i).join("/");
      if (!this.app.vault.getAbstractFileByPath(dirPath)) {
        await this.app.vault.createFolder(dirPath);
      }
    }
  }
  // ── # autocomplete ──
  registerAutocompleteOverride() {
    this.registerEditorExtension(
      (0, import_autocomplete.autocompletion)({
        override: [this.getPageCompletion.bind(this)]
      })
    );
  }
  getPageCompletion(context) {
    const match = context.matchBefore(/#[-\p{L}\p{N}\p{Script=Han}_\/]*$/u);
    if (!match || match.text === "#" && !context.explicit)
      return null;
    const query = match.text.slice(1).toLowerCase();
    const { vault, metadataCache } = this.app;
    const seen = /* @__PURE__ */ new Set();
    const suggestions = [];
    for (const file of vault.getMarkdownFiles()) {
      if (file.basename.toLowerCase().includes(query) && !seen.has(file.basename)) {
        seen.add(file.basename);
        suggestions.push({ label: file.basename, apply: file.basename });
      }
      const cache = metadataCache.getCache(file.path);
      const fm = cache == null ? void 0 : cache.frontmatter;
      if (!fm)
        continue;
      for (const key of ["alias", "aliases"]) {
        const val = fm[key];
        const list = typeof val === "string" ? [val] : Array.isArray(val) ? val.filter((v) => typeof v === "string") : [];
        for (const alias of list) {
          if (seen.has(alias))
            continue;
          if (alias.toLowerCase().includes(query)) {
            seen.add(alias);
            suggestions.push({
              label: alias,
              apply: alias,
              detail: `\u2192 ${file.basename}`
            });
          }
        }
      }
    }
    if (suggestions.length === 0)
      return null;
    suggestions.sort((a, b) => {
      const aLC = a.label.toLowerCase();
      const bLC = b.label.toLowerCase();
      if (aLC === query)
        return -1;
      if (bLC === query)
        return 1;
      if (aLC.startsWith(query) && !bLC.startsWith(query))
        return -1;
      if (!aLC.startsWith(query) && bLC.startsWith(query))
        return 1;
      return aLC.localeCompare(bLC);
    });
    return {
      from: match.from + 1,
      options: suggestions.slice(0, 20).map((s) => ({
        label: s.label,
        detail: s.detail,
        apply: s.apply
      }))
    };
  }
  // ── settings persistence ──
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var TagToPageSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /** Get translated string for the current language. */
  t(key) {
    var _a, _b, _c, _d;
    const lang = this.plugin.settings.language;
    return (_d = (_c = (_a = LANG[lang]) == null ? void 0 : _a[key]) != null ? _c : (_b = LANG["en"]) == null ? void 0 : _b[key]) != null ? _d : key;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("tag-to-page-settings");
    const hero = containerEl.createDiv({ cls: "tag-to-page-settings__hero" });
    const icon = hero.createDiv({
      cls: "tag-to-page-settings__icon",
      text: "#"
    });
    icon.setAttr("aria-hidden", "true");
    const heroBody = hero.createDiv({ cls: "tag-to-page-settings__hero-body" });
    heroBody.createEl("h2", { text: this.t("settingHeader") });
    heroBody.createEl("p", { text: this.t("pluginDesc") });
    const heroMeta = heroBody.createDiv({ cls: "tag-to-page-settings__hero-meta" });
    heroMeta.createSpan({
      cls: "tag-to-page-settings__version",
      text: `v${this.plugin.manifest.version}`
    });
    const repositoryLink = heroMeta.createEl("a", {
      text: this.t("repository"),
      href: "https://github.com/agarcabin/obsdian-tag-to-page"
    });
    repositoryLink.setAttr("target", "_blank");
    repositoryLink.setAttr("rel", "noopener");
    const preferencesSection = containerEl.createDiv({
      cls: "tag-to-page-settings__section"
    });
    const preferencesHeader = preferencesSection.createDiv({
      cls: "tag-to-page-settings__section-header"
    });
    preferencesHeader.createEl("h3", { text: this.t("preferences") });
    preferencesHeader.createEl("p", { text: this.t("preferencesDesc") });
    const languageSetting = new import_obsidian.Setting(preferencesSection).setName(this.t("language")).setDesc(this.t("languageDesc")).addDropdown(
      (dropdown) => dropdown.addOption("zh", "\u4E2D\u6587").addOption("en", "English").setValue(this.plugin.settings.language).onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    languageSetting.settingEl.addClass("tag-to-page-settings__setting");
    const behaviorSection = containerEl.createDiv({
      cls: "tag-to-page-settings__section"
    });
    const behaviorHeader = behaviorSection.createDiv({
      cls: "tag-to-page-settings__section-header"
    });
    behaviorHeader.createEl("h3", { text: this.t("behavior") });
    behaviorHeader.createEl("p", { text: this.t("behaviorDesc") });
    const autocompleteSetting = new import_obsidian.Setting(behaviorSection).setName(this.t("autocompleteName")).setDesc(this.t("autocompleteDesc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autocompleteOn).onChange(async (value) => {
        this.plugin.settings.autocompleteOn = value;
        await this.plugin.saveSettings();
        const id = this.plugin.manifest.id;
        const pluginManager = this.plugin.app.plugins;
        await pluginManager.disablePlugin(id);
        await pluginManager.enablePlugin(id);
      })
    );
    autocompleteSetting.settingEl.addClass("tag-to-page-settings__setting");
    const notice = behaviorSection.createDiv({
      cls: "tag-to-page-settings__notice"
    });
    notice.createDiv({
      cls: "tag-to-page-settings__notice-title",
      text: this.t("autocompleteNotice")
    });
    notice.createDiv({
      cls: "tag-to-page-settings__notice-text",
      text: this.t("autocompleteNoticeDesc")
    });
  }
};
